displayName=Clan War Board
author=Oyama
support=https://github.com/ItMeansBigMountain/clan-war-board-osrs
description=Lets OSRS clans arrange CWA and Wilderness fights on an online war board.
tags=clan,war,pvp,cwa,wilderness
plugins=com.itmeansbigmountain.clanwarboard.ClanWarBoardPlugin
version=1.0.0
build=standard
